name: Update Flight Data
run-name: Fetch Data
on:
  schedule:
    - cron: '0,1,2,3,4,5,6,7,8,9,10,30,49,50,51,52,53,54,55,56,57,58,59 * * * *'

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Fetch flight data from OpenSky Network API
        run: |
          javac dataMan.java
          java dataMan
